name = "internet-positive-api"
main = "src/index.js"
compatibility_date = "2026-05-19"
workers_dev = true

[vars]
APP_NAME = "Internet Positive Compliance API"
PUBLIC_CHECK_ENABLED = "true"
CACHE_TTL_SECONDS = "600"
RATE_LIMIT_MAX = "60"
RATE_LIMIT_WINDOW_SECONDS = "60"
PROVIDER_MODE = "generic"
PROVIDER_METHOD = "POST"
PROVIDER_URL = "https://trustpositif.id/api/v1/check"
ALLOWED_ORIGINS = "*"

[triggers]
crons = ["*/10 * * * *"]

[[kv_namespaces]]
binding = "IPOS_CACHE"
id = "7871d779582c48fcba3ab83f60dc3493"

[[kv_namespaces]]
binding = "IPOS_RATE_LIMIT"
id = "acbfe8c3bd5e499894065487b2b6316e"

[[kv_namespaces]]
binding = "IPOS_MONITOR"
id = "723857cb785c413084ce89dd422f148c"
